name: Embedbase core CI

on:
  pull_request:
    paths:
      - 'embedbase/**'
  push:
    branches:
      - main
      - next
      - rc
    paths:
      - 'embedbase/**'
      # when pyproject.toml changes
      - "pyproject.toml"
      - "tests/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2

      - name: Install dependencies
        run: |
          poetry install

      - name: Read EMBEDBASE_TEST_CONFIG JSON secret and write it to config.yaml
        env:
          EMBEDBASE_TEST_CONFIG: ${{ secrets.EMBEDBASE_TEST_CONFIG }}
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
          chmod +x yq
          echo $EMBEDBASE_TEST_CONFIG | yq -P > config.yaml

      - name: Run tests
        run: |
          docker run --rm --name pgvector -e POSTGRES_DB=embedbase -e POSTGRES_PASSWORD=localdb -p 5432:5432 -p 8080:8080 -d ankane/pgvector
          while ! docker exec pgvector pg_isready -U postgres; do sleep 1; done
          poetry run pytest --cov-report=html --cov=embedbase --ignore=sdk --ignore=hosted;poetry run coverage-badge -o assets/images/coverage.svg -f;docker stop pgvector



